global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your@example.com'
  smtp_auth_username: 'your@example.com'
  smtp_auth_password: 'complex password'      #first add password in gmail shouldnt password default gmail
  smtp_require_tls: true

route:
  receiver: 'gmail-notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: 'your@example.com'
