services:
  prometheus:
    image: prom/prometheus:latest
    container_name: promethous
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - ./rules.yml:/etc/prometheus/rules.yml
    restart: always
  Grafana:
     image: grafana/grafana
     container_name: Grafana
     ports:
       - "3000:3000"
     volumes:
       - Grafana_data:/var/lib/grafana
     restart: always
  node-exporter:
     image: prom/node-exporter:latest
     container_name: node-exporter
     pid: "host"
     restart: always
     ports:
       - "9100:9100"
     volumes:
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
       - /:/rootfs:ro
     command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  alertmanager:
     image: prom/alertmanager
     ports:
       - '9093:9093'
     volumes:
       - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
     command:
       - '--config.file=/etc/alertmanager/alertmanager.yml'
     restart: always
volumes:
    prometheus_data:
    Grafana_data:
