services:
  prometheus:
    image: prom/prometheus:latest
    container_name: promethous
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - ./rules.yml:/etc/prometheus/rules.yml
    restart: always
  Grafana:
     image: grafana/grafana
     container_name: Grafana
     ports:
       - "3000:3000"
     volumes:
       - Grafana_data:/var/lib/grafana
     restart: always
  node-exporter:
     image: prom/node-exporter:latest
     container_name: node-exporter
     pid: "host"
     restart: always
     ports:
       - "9100:9100"
     volumes:
          # Mount /proc directory from host to provide access to system-level metrics (CPU, memory, etc.)
       - /proc:/host/proc:ro
          # Mount /sys directory from host for accessing kernel and hardware info
       - /sys:/host/sys:ro
         # Mount entire root filesystem in read-only mode to allow node-exporter access to full system data
       - /:/rootfs:ro
     command:
      - '--path.procfs=/host/proc'  #Path to the host's proc filesystem, for process information
      - '--path.sysfs=/host/sys'     # Path to the host's sys filesystem, for kernel and device configuration
      - '--path.rootfs=/rootfs'   # Path to the host's root filesystem, for system file access 
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'   #Command configuration for ignoring specific filesystem mount points.
# This regular expression excludes the following directories from being collected:
# - /sys
# - /proc
# - /dev
# - /host
# - /etc
# These directories are typically system or virtual filesystems that do not provide useful
# disk usage metrics for monitoring purposes.
# The regular expression ensures these paths are ignored at the root level or in their subdirectories
  alertmanager:
     image: prom/alertmanager
     ports:
       - '9093:9093'
     volumes:
       - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
     command:
       - '--config.file=/etc/alertmanager/alertmanager.yml'
     restart: always
volumes:
    prometheus_data:
    Grafana_data:
